version: '3'
services:
  db:
    image: mysql:5.7
    # M1使うときはコメント解除
    # platfrom: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # デバック用
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
